### ISSUE TITLE
Got Error 

### ISSUE THREAD

**Issue by ntaapp** [EleutherAI/DALLE-mtf#10]
I got error when run the command:
`python3 src/data/create_tfrecords.py`

Error: 
`Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 6.36MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 3.31MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 7.19MB/s]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "src/data/create_tfrecords.py", line 184, in <module>
    tokenizer=None)
  File "src/data/create_tfrecords.py", line 158, in create_paired_dataset
    data = load_jsonl(path)
  File "src/data/create_tfrecords.py", line 32, in load_jsonl
    with open(input_path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/coco/coco_captions.jsonl'
0it [00:00, ?it/s]`

**Comment by ntaapp** [comment]
Any one know how to fix?
Thanks
